version: '3.5'

services:
  #### MySQl ####
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:5.7-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      retries: 3
      timeout: 5s

    #### End ####

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - /sessions
    networks:
      - mysql



volumes:
  mysql:

networks:
  mysql:
    driver: bridge
