version: '3.5'

services:
  #### Redis ####
  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine3.13
    # command: redis-server --requirepass $PASSWORD --appendonly yes
    environment:
      - PASSWORD=password
    volumes:
      - redis:/data
    networks:
      - redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
      #### End ####

volumes:
  redis:

networks:
  redis:
    driver: bridge