version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-02-17T01-15-57Z
  command: server --console-address ":9001" /data
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioroot
    MINIO_ROOT_PASSWORD: miniopass
    #MINIO_SERVER_URL: "https://minio.mydomain.com"
    MINIO_BROWSER_REDIRECT_URL: "https://minio.mydomain.com/ui"
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./data:/data
    #- data1-2:/data2
    ports:
      - "127.0.0.1:10000:9000"
      - "127.0.0.1:9001:9001"
