version: '3.5'

services:
  #### PostgreSQL and PgAdmin ####
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13.2-alpine
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init-postgres:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 3s
      timeout: 5s
      retries: 3

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: always
  #### End ####

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge