version: '3.5'

services:
  #### MySQl ####
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "password" ]
      retries: 3
      timeout: 5s

  #### End ####

volumes:
  mysql:

networks:
  mysql:
    driver: bridge